/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import {HTMLStencilElement, JSXBase} from '@stencil/core/internal';
import {FillStyle, Size} from './typings/props';
export namespace Components {
  interface GiotramuLogo {
    column: boolean;
    fillColor: FillStyle;
    size: Size;
  }
  interface GiotramuSign {
    fillColor: FillStyle;
    size: Size;
  }
  interface GiotramuTypo {
    fillColor: FillStyle;
    size: Size;
  }
}
declare global {
  interface HTMLGiotramuLogoElement
    extends Components.GiotramuLogo,
      HTMLStencilElement {}
  var HTMLGiotramuLogoElement: {
    prototype: HTMLGiotramuLogoElement;
    new (): HTMLGiotramuLogoElement;
  };
  interface HTMLGiotramuSignElement
    extends Components.GiotramuSign,
      HTMLStencilElement {}
  var HTMLGiotramuSignElement: {
    prototype: HTMLGiotramuSignElement;
    new (): HTMLGiotramuSignElement;
  };
  interface HTMLGiotramuTypoElement
    extends Components.GiotramuTypo,
      HTMLStencilElement {}
  var HTMLGiotramuTypoElement: {
    prototype: HTMLGiotramuTypoElement;
    new (): HTMLGiotramuTypoElement;
  };
  interface HTMLElementTagNameMap {
    'giotramu-logo': HTMLGiotramuLogoElement;
    'giotramu-sign': HTMLGiotramuSignElement;
    'giotramu-typo': HTMLGiotramuTypoElement;
  }
}
declare namespace LocalJSX {
  interface GiotramuLogo {
    column?: boolean;
    fillColor?: FillStyle;
    size?: Size;
  }
  interface GiotramuSign {
    fillColor?: FillStyle;
    size?: Size;
  }
  interface GiotramuTypo {
    fillColor?: FillStyle;
    size?: Size;
  }
  interface IntrinsicElements {
    'giotramu-logo': GiotramuLogo;
    'giotramu-sign': GiotramuSign;
    'giotramu-typo': GiotramuTypo;
  }
}
export {LocalJSX as JSX};
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'giotramu-logo': LocalJSX.GiotramuLogo &
        JSXBase.HTMLAttributes<HTMLGiotramuLogoElement>;
      'giotramu-sign': LocalJSX.GiotramuSign &
        JSXBase.HTMLAttributes<HTMLGiotramuSignElement>;
      'giotramu-typo': LocalJSX.GiotramuTypo &
        JSXBase.HTMLAttributes<HTMLGiotramuTypoElement>;
    }
  }
}
